"""Idempotent dedup + merge of staged entries into the YAML database.

The agent never writes the DB. This deterministic step:
  * keys existing entries by ``dedup_key`` (arxiv_id > repo > normalized title),
  * adds genuinely new entries with a recomputed canonical id (ignoring the LLM's id),
  * for matches, fills only *empty* fields from the incoming record — never clobbering
    human-edited values — so re-runs converge and produce no PR churn.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

from agent.schema import Entry, Links, derive_id
from pipeline import db


@dataclass
class MergeReport:
    added: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return bool(self.added or self.updated)


def _fill_missing(existing: Entry, incoming: Entry) -> Entry:
    """Return ``existing`` unchanged, or a copy with empty fields filled from ``incoming``."""
    updates: dict = {}

    ex_links = existing.links.model_dump(mode="python")
    in_links = incoming.links.model_dump(mode="python")
    link_changed = False
    merged_links = {}
    for k, ex_v in ex_links.items():
        in_v = in_links.get(k)
        if ex_v is None and in_v is not None:
            merged_links[k] = in_v
            link_changed = True
        else:
            merged_links[k] = ex_v
    if link_changed:
        updates["links"] = Links(**merged_links)

    for f in ("year", "arxiv_id", "repo", "thumbnail", "summary_ja"):
        if getattr(existing, f) in (None, "") and getattr(incoming, f) not in (None, ""):
            updates[f] = getattr(incoming, f)

    if not existing.authors and incoming.authors:
        updates["authors"] = incoming.authors
    if not existing.tags and incoming.tags:
        updates["tags"] = incoming.tags

    if not updates:
        return existing
    return existing.model_copy(update=updates)


def merge(staged: list[Entry], existing: list[Entry]) -> tuple[list[Entry], MergeReport]:
    by_key: dict[str, Entry] = {e.key: e for e in existing}
    report = MergeReport()
    for e in staged:
        k = e.key
        if k in by_key:
            merged = _fill_missing(by_key[k], e)
            if merged is by_key[k] or merged == by_key[k]:
                report.skipped.append(k)
            else:
                by_key[k] = merged
                report.updated.append(k)
        else:
            canonical = e.model_copy(update={"id": derive_id(e.title, e.arxiv_id, e.repo)})
            by_key[k] = canonical
            report.added.append(k)
    return list(by_key.values()), report


def write_pr_body(path: Path, report: MergeReport, merged: list[Entry]) -> None:
    by_key = {e.key: e for e in merged}
    lines = ["## Weekly catalog update", ""]
    lines.append(f"- **Added:** {len(report.added)}  ·  **Updated:** {len(report.updated)}  "
                 f"·  **Skipped (dupes):** {len(report.skipped)}")
    lines.append("")
    if report.added:
        lines.append("### New entries")
        for k in report.added:
            e = by_key.get(k)
            if e:
                lines.append(f"- **{e.title}** — `{e.area}/{e.task}` ({e.kind}) · {e.links.primary() or ''}")
        lines.append("")
    if report.updated:
        lines.append("### Enriched entries")
        for k in report.updated:
            e = by_key.get(k)
            if e:
                lines.append(f"- {e.title} — `{e.area}/{e.task}`")
        lines.append("")
    lines.append("_Auto-generated by the weekly research agent. Please review before merging._")
    path.write_text("\n".join(lines), encoding="utf-8")


def _load_staged(path: Path) -> list[Entry]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    records = raw.get("entries", []) if isinstance(raw, dict) else raw
    return [Entry.model_validate(r) for r in records]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Merge staged entries into the YAML DB.")
    ap.add_argument("--staged", required=True, help="Path to staged.json from the agent.")
    ap.add_argument("--data-dir", default=None)
    ap.add_argument("--pr-body", default=None, help="Optional path to write a markdown changelog.")
    args = ap.parse_args(argv)

    staged_path = Path(args.staged)
    if not staged_path.exists():
        print(f"No staged file at {staged_path}; nothing to merge.")
        return 0

    staged = _load_staged(staged_path)
    existing = db.load_all(args.data_dir)
    merged, report = merge(staged, existing)
    db.save_split(merged, args.data_dir)

    print(f"merge: added={len(report.added)} updated={len(report.updated)} "
          f"skipped={len(report.skipped)} total={len(merged)}")
    if args.pr_body:
        write_pr_body(Path(args.pr_body), report, merged)
    return 0


if __name__ == "__main__":
    sys.exit(main())
